const API='/api/v1',UFA=[54.7351,55.9587],state={start:null,finish:null,picking:'start',markers:{},routeLayer:null};
const map=L.map('map',{zoomControl:false}).setView(UFA,14);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);L.control.zoom({position:'bottomleft'}).addTo(map);
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],form=$('#routeForm'),message=$('#formMessage');
function minutesBetween(a,b){const x=a.split(':').map(Number),y=b.split(':').map(Number),d=y[0]*60+y[1]-x[0]*60-x[1];return d>0?d:d+1440}
function setMarker(kind,point,label){state[kind]={lat:point.lat,lon:point.lng};if(state.markers[kind])state.markers[kind].remove();state.markers[kind]=L.marker(point).addTo(map).bindTooltip(label,{permanent:true,direction:'top',offset:[0,-12]});state.picking=kind==='start'?'finish':null;$('#mapHint').textContent=state.picking?'Теперь укажите финиш':'Точки выбраны — нажмите Go!'}
map.on('click',e=>{const kind=state.picking||'finish';setMarker(kind,e.latlng,kind==='start'?'Старт':'Финиш');reverseGeocode(e.latlng).then(a=>$(`#${kind}Input`).value=a).catch(()=>{})});
$$('[data-pick]').forEach(b=>b.addEventListener('click',()=>{state.picking=b.dataset.pick;$('#mapHint').textContent=state.picking==='start'?'Укажите старт на карте':'Укажите финиш на карте'}));
async function geocode(q){const r=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=ru&q=${encodeURIComponent(q)}`,{headers:{Accept:'application/json'}}),[x]=await r.json();if(!r.ok||!x)throw Error(`Адрес не найден: ${q}`);return{lat:Number(x.lat),lon:Number(x.lon)}}
async function reverseGeocode(p){const r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${p.lat}&lon=${p.lng}`),d=await r.json();return d.display_name?.split(',').slice(0,3).join(', ')||`${p.lat.toFixed(5)}, ${p.lng.toFixed(5)}`}
async function api(path,options={}){const r=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.details||d.error||`Ошибка API ${r.status}`);return d}
function interests(){const active=new Set($$('#interestPicker .active').map(x=>x.dataset.interest));return Object.fromEntries($$('#interestPicker button').map(x=>[x.dataset.interest,active.has(x.dataset.interest)?1:.1]))}
async function ensurePoints(){const jobs=[];if(!state.start)jobs.push(geocode($('#startInput').value).then(p=>setMarker('start',L.latLng(p.lat,p.lon),'Старт')));if(!state.finish)jobs.push(geocode($('#finishInput').value).then(p=>setMarker('finish',L.latLng(p.lat,p.lon),'Финиш')));await Promise.all(jobs)}
function esc(v){const e=document.createElement('div');e.textContent=v??'';return e.innerHTML}
function render(route){if(state.routeLayer)state.routeLayer.remove();state.routeLayer=L.geoJSON(route.geojson,{style:{color:'#3c2c29',weight:6,opacity:.9,lineCap:'round'}}).addTo(map);route.waypoints.filter(p=>p.type==='place').forEach(p=>L.circleMarker([p.location.lat,p.location.lon],{radius:12,color:'#fff',weight:4,fillColor:'#ff625f',fillOpacity:1}).addTo(state.routeLayer).bindPopup(`<strong>${esc(p.place_name)}</strong><br>${esc(p.category)}<br>${p.duration_min} мин.`));map.fitBounds(state.routeLayer.getBounds(),{padding:[45,45]});$('#summaryTime').textContent=`${route.total_duration_min} мин`;$('#summaryDistance').textContent=`${(route.total_distance_meters/1000).toFixed(1)} км`;$('#routeSummary').classList.remove('hidden');$('#resultTitle').textContent=`Прогулка на ${route.total_duration_min} минут`;$('#reasons').innerHTML=route.match_reasons.map(x=>`<span>${esc(x)}</span>`).join('');$('#waypoints').innerHTML=route.waypoints.map((p,i)=>{const n=p.type==='start'?'Начало маршрута':p.type==='finish'?'Финиш':p.place_name,d=p.type==='place'?`${p.category} · ${p.duration_min} мин · ${(p.distance_from_prev_meters||0).toFixed(0)} м пешком`:`${p.location.lat.toFixed(4)}, ${p.location.lon.toFixed(4)}`;return`<li data-order="${i+1}"><strong>${esc(n)}</strong><span>${esc(d)}</span></li>`}).join('');form.classList.add('hidden');$('#results').classList.remove('hidden')}
form.addEventListener('submit',async e=>{e.preventDefault();const b=$('#goButton');b.disabled=true;message.textContent='Ищем места и собираем лучший маршрут…';try{await ensurePoints();let guest=localStorage.getItem('routeGuest')||Date.now();const profile=await api('/users/',{method:'POST',body:JSON.stringify({name:'Путешественник',email:`guest-${guest}@go.local`,interests:interests()})});localStorage.setItem('routeGuest',guest);const route=await api('/routes/build',{method:'POST',body:JSON.stringify({user_ids:[profile.id],budget_minutes:minutesBetween($('#timeFrom').value,$('#timeTo').value),start:state.start,finish:state.finish})});render(route)}catch(err){console.error(err);message.textContent=err.message.includes('no places')?'Места не найдены. Добавьте TWOGIS_API_KEY или загрузите OSM-данные.':err.message}finally{b.disabled=false}});
$('#editButton').addEventListener('click',()=>{$('#results').classList.add('hidden');form.classList.remove('hidden')});$('#togglePlanner').addEventListener('click',()=>$('#planner').classList.toggle('collapsed'));
$$('#interestPicker button, #pacePicker button').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.pace)$$('#pacePicker button').forEach(x=>x.classList.remove('active'));b.classList.toggle('active')}));
$('#locateButton').addEventListener('click',()=>navigator.geolocation?.getCurrentPosition(p=>{const x=L.latLng(p.coords.latitude,p.coords.longitude);setMarker('start',x,'Вы здесь');map.setView(x,15)},()=>$('#mapHint').textContent='Не удалось получить геопозицию'));
Promise.all([geocode($('#startInput').value),geocode($('#finishInput').value)]).then(([a,b])=>{setMarker('start',L.latLng(a.lat,a.lon),'Старт');setMarker('finish',L.latLng(b.lat,b.lon),'Финиш');map.fitBounds([[a.lat,a.lon],[b.lat,b.lon]],{padding:[60,60]})}).catch(()=>{});
