// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/routes/build": {
            "post": {
                "description": "Generates an optimized walking route with ordered stops, GeoJSON geometry, duration, and match reasons",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "routes"
                ],
                "summary": "Build personalized group pedestrian route",
                "parameters": [
                    {
                        "description": "Route parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.BuildRouteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BuildRouteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users": {
            "post": {
                "description": "Creates a new user profile or updates interests",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create or update user profile",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateOrUpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}": {
            "get": {
                "description": "Retrieves profile information and interest weights for a user by UUID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.BuildRouteRequest": {
            "type": "object",
            "required": [
                "budget_minutes",
                "finish",
                "start",
                "user_ids"
            ],
            "properties": {
                "budget_minutes": {
                    "type": "integer",
                    "example": 120
                },
                "finish": {
                    "$ref": "#/definitions/dto.PointDTO"
                },
                "start": {
                    "$ref": "#/definitions/dto.PointDTO"
                },
                "user_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[\"a4d3f56b-3cb8-45a7-96a9-83bc815b8b92\"]"
                    ]
                }
            }
        },
        "dto.BuildRouteResponse": {
            "type": "object",
            "properties": {
                "geojson": {
                    "$ref": "#/definitions/entity.GeoJSONFeature"
                },
                "match_reasons": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[\"Высокое совпадение по кофе (0.85)\"]"
                    ]
                },
                "match_score": {
                    "type": "number",
                    "example": 0.89
                },
                "route_id": {
                    "type": "string",
                    "example": "e2b5e28a-6950-482a-aef2-ecbb903ca914"
                },
                "total_distance_meters": {
                    "type": "number",
                    "example": 2200
                },
                "total_duration_min": {
                    "type": "integer",
                    "example": 85
                },
                "waypoints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.RoutePointResponse"
                    }
                }
            }
        },
        "dto.CreateOrUpdateUserRequest": {
            "type": "object",
            "required": [
                "email",
                "name"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "alexey@example.com"
                },
                "interests": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "format": "float64"
                    },
                    "example": {
                        "art": 0.4,
                        "coffee": 0.9,
                        "parks": 0.7
                    }
                },
                "name": {
                    "type": "string",
                    "example": "Алексей"
                }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "string",
                    "example": "start coordinates are outside valid bounds"
                },
                "error": {
                    "type": "string",
                    "example": "invalid request payload"
                }
            }
        },
        "dto.PointDTO": {
            "type": "object",
            "properties": {
                "lat": {
                    "type": "number",
                    "example": 55.751244
                },
                "lon": {
                    "type": "number",
                    "example": 37.618423
                }
            }
        },
        "dto.RoutePointResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string",
                    "example": "coffee"
                },
                "distance_from_prev_meters": {
                    "type": "number",
                    "example": 450
                },
                "duration_from_prev_min": {
                    "type": "number",
                    "example": 6.5
                },
                "duration_min": {
                    "type": "integer",
                    "example": 25
                },
                "location": {
                    "$ref": "#/definitions/dto.PointDTO"
                },
                "order": {
                    "type": "integer"
                },
                "place_name": {
                    "type": "string",
                    "example": "Кофейня Зерно"
                },
                "type": {
                    "type": "string",
                    "example": "place"
                }
            }
        },
        "dto.UserResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "example": "alexey@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "a4d3f56b-3cb8-45a7-96a9-83bc815b8b92"
                },
                "interests": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "format": "float64"
                    }
                },
                "name": {
                    "type": "string",
                    "example": "Алексей"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "entity.GeoJSONFeature": {
            "type": "object",
            "properties": {
                "geometry": {
                    "$ref": "#/definitions/entity.GeoJSONGeometry"
                },
                "properties": {
                    "type": "object",
                    "additionalProperties": true
                },
                "type": {
                    "description": "\"Feature\"",
                    "type": "string"
                }
            }
        },
        "entity.GeoJSONGeometry": {
            "type": "object",
            "properties": {
                "coordinates": {
                    "description": "Array of [lon, lat] pairs",
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "number",
                            "format": "float64"
                        }
                    }
                },
                "type": {
                    "description": "\"LineString\"",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Team Route Optimizer API",
	Description:      "Backend-сервис оркестрации персонализированных пешеходных маршрутов",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
